[package]
name = "libwater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "5.0.1"
reqwest = "0.11.24"
tar = "0.4.40"
xz = "0.1.0"
