# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "libh2o"
version = "0.1.0"
edition = "2021"

#[lib]
#crate-type = ["cdylib"]

[dependencies]
dirs = "5.0.1"
reqwest = "0.11.24"
serde = "1.0.196"
tar = "0.4.40"
xz = "0.1.0"
